ALTER TABLE RegisteredUsers
MODIFY COLUMN auth_token TEXT UNIQUE NOT NULL,
MODIFY COLUMN user_name TEXT UNIQUE NOT NULL;

ALTER TABLE CodingActivities
MODIFY COLUMN project_name TEXT,
MODIFY COLUMN language TEXT,
MODIFY COLUMN editor_name TEXT,
MODIFY COLUMN hostname TEXT;
